---
title: "Random Sampling in fire perimeters"
author: "Anna Talucci"
date: "6/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Overview

Generate random points within the fire perimter polygons in order to sample individual pixels in GEE. Issue with sampling in GEE with stratified sample since it was a classified image. Issues exporting dNBR image because it is too large.


# Packages
```{r}
library(sf)
library(sp)
library(raster)
library(rgdal)
library(ggspatial)
library(dplyr)
library(tidyr)
library(stringr)
library(lwgeom)
```


# Polygons

```{r}
fp2001 = st_read("../data/clean-shapefile/fires2001.shp") 
fp2002 = st_read("../data/clean-shapefile/fires2002.shp")
fp2003 = st_read("../data/clean-shapefile/fires2003.shp")
fp2004 = st_read("../data/clean-shapefile/fires2004.shp")
fp2005 = st_read("../data/clean-shapefile/fires2005.shp")
```

```{r}
plot(st_geometry(fp2001))
```

```{r}
head(fp2001)
```


```{r}
summary(fp2001)
summary(fp2002)
summary(fp2003)
summary(fp2004)
summary(fp2005)
```
str_pad(string, width, side = c("left", "right", "both"), pad = " ")
```{r}
fp2001_1 = fp2001 %>% 
  mutate(cntry_code = 'RU') %>%
  mutate(fire_no = str_pad(ID_obj, 4, side = "left", pad =  0)) %>%
  mutate(fire_id = paste(cntry_code, fire_yr, fire_no, sep = '_')) %>%
  mutate(total_fires = 771) %>% 
  mutate(prct_area = area_m*0.0001) %>%
  mutate(pixels = round((prct_area/90), digits = 0))

fp2001_1
```

```{r}
sum(fp2001_1$pixels)
```

```{r}
set.seed(1)
subset2001 = fp2001 %>% 
  mutate(total_fires = 771) %>%
  mutate(random = sample(771, size = nrow(fp2001), replace = FALSE)) %>%
  filter(random <= 10) %>%
  mutate(prct_area_1 = area_m*0.001) %>%
  mutate(pixels_1 = round((prct_area_1/90), digits = 0))

subset2001
```

```{r}
point2001 = st_sample(subset2001, size = subset2001$pixels_1, type = "random", exact = TRUE)
```
```{r}
head(point2001)
```

```{r}
plot(st_geometry(subset2001))
plot(point2001, add=TRUE)
```

```{r}
st_write(point2001, "../outputs/points2001.shp", driver="ESRI Shapefile") 
```

```{r}
point2001_all = st_sample(fp2001_1, size = fp2001_1$pixels, type = "random", exact = TRUE)
```

```{r}
point2001_all
```
```{r}
pt_2001 = st_sf(point2001_all)
```

```{r}
pt2001_all = st_join(pt_2001, fp2001_1, join = st_within)
head(pt2001_all)
```

```{r}
summary(pt2001_all)
```


```{r}
st_write(pt2001_all, "../outputs/points2001_all.shp", driver="ESRI Shapefile") 
```